version: "3"

services:
  nginx:
    build: "./dockerfile/nginx"
    container_name: ng121
    ports:
      - "1080:80"
    volumes:
      - /Users/sunqiaoyu/GolandProjects/go/src/lnmp/config/nginx/conf.d:/etc/nginx/conf.d
      - /Users/sunqiaoyu/GolandProjects/go/src/lnmp/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Users/sunqiaoyu/GolandProjects/go/src/lnmp/www:/usr/share/nginx/html
      - /Users/sunqiaoyu/GolandProjects/go/src/lnmp/logs/nginx:/var/log/nginx/
    networks:
      - lnmp
    depends_on:
      - php
  php:
    build: "./dockerfile/php-fpm"
    container_name: php74
    volumes:
      - /Users/sunqiaoyu/GolandProjects/go/src/lnmp/www:/usr/share/nginx/html
      - /Users/sunqiaoyu/GolandProjects/go/src/lnmp/logs/php:/usr/share/nginx/logs
      - /Users/sunqiaoyu/GolandProjects/go/src/lnmp/config/php-fpm/php:/usr/local/etc/php
      - /Users/sunqiaoyu/GolandProjects/go/src/lnmp/config/php-fpm/php-fpm.d:/usr/local/etc/php-fpm.d
    networks:
      - lnmp
    depends_on:
      - redis
      - mysql
  redis:
    build: "./dockerfile/redis"
    container_name: redis505
    ports:
      - "16379:6379"
    volumes:
      - /Users/sunqiaoyu/GolandProjects/go/src/lnmp/config/redis/redis.conf:/etc/redis/redis.conf
      - /Users/sunqiaoyu/GolandProjects/go/src/lnmp/data/redis:/data/data
      - /Users/sunqiaoyu/GolandProjects/go/src/lnmp/logs/redis:/data/logs
    networks:
      - lnmp
  mysql:
    build: "./dockerfile/mysql"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: root
    ports:
      - "13306:3306"
    volumes:
      - /Users/sunqiaoyu/GolandProjects/go/src/lnmp/config/mysql/my.cnf:/etc/my.cnf
      - /Users/sunqiaoyu/GolandProjects/go/src/lnmp/data/mysql:/var/lib/mysql
      - /Users/sunqiaoyu/GolandProjects/go/src/lnmp/logs/mysql:/var/log/mysql
    networks:
      - lnmp
networks:
  lnmp: